/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;
import org.transsonic.trustgame.data.trustgame.enums.CarrierService;
import org.transsonic.trustgame.data.trustgame.enums.CarrierSustainability;
import org.transsonic.trustgame.data.trustgame.tables.Carrier;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarrierRecord extends UpdatableRecordImpl<CarrierRecord> implements Record17<Integer, String, String, byte[], CarrierService, CarrierSustainability, String, String, String, String, String, String, byte[], String, byte[], String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.carrier.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.carrier.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.carrier.Name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.carrier.Name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>trustgame.carrier.Slogan</code>.
     */
    public void setSlogan(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.carrier.Slogan</code>.
     */
    public String getSlogan() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trustgame.carrier.Logo</code>.
     */
    public void setLogo(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.carrier.Logo</code>.
     */
    public byte[] getLogo() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>trustgame.carrier.Service</code>.
     */
    public void setService(CarrierService value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustgame.carrier.Service</code>.
     */
    public CarrierService getService() {
        return (CarrierService) get(4);
    }

    /**
     * Setter for <code>trustgame.carrier.Sustainability</code>.
     */
    public void setSustainability(CarrierSustainability value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustgame.carrier.Sustainability</code>.
     */
    public CarrierSustainability getSustainability() {
        return (CarrierSustainability) get(5);
    }

    /**
     * Setter for <code>trustgame.carrier.CompanyDescription</code>. HTML or Markdown
     */
    public void setCompanydescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>trustgame.carrier.CompanyDescription</code>. HTML or Markdown
     */
    public String getCompanydescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>trustgame.carrier.WebsiteURL</code>.
     */
    public void setWebsiteurl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>trustgame.carrier.WebsiteURL</code>.
     */
    public String getWebsiteurl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>trustgame.carrier.OfficialReportDescription</code>. HTML or Markdown
     */
    public void setOfficialreportdescription(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>trustgame.carrier.OfficialReportDescription</code>. HTML or Markdown
     */
    public String getOfficialreportdescription() {
        return (String) get(8);
    }

    /**
     * Setter for <code>trustgame.carrier.OfficialReport</code>. HTML or Markdown
     */
    public void setOfficialreport(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>trustgame.carrier.OfficialReport</code>. HTML or Markdown
     */
    public String getOfficialreport() {
        return (String) get(9);
    }

    /**
     * Setter for <code>trustgame.carrier.CarrierType</code>.
     */
    public void setCarriertype(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>trustgame.carrier.CarrierType</code>.
     */
    public String getCarriertype() {
        return (String) get(10);
    }

    /**
     * Setter for <code>trustgame.carrier.GooglePage</code>.
     */
    public void setGooglepage(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>trustgame.carrier.GooglePage</code>.
     */
    public String getGooglepage() {
        return (String) get(11);
    }

    /**
     * Setter for <code>trustgame.carrier.GoogleImage</code>.
     */
    public void setGoogleimage(byte[] value) {
        set(12, value);
    }

    /**
     * Getter for <code>trustgame.carrier.GoogleImage</code>.
     */
    public byte[] getGoogleimage() {
        return (byte[]) get(12);
    }

    /**
     * Setter for <code>trustgame.carrier.CarrierWebPage</code>.
     */
    public void setCarrierwebpage(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>trustgame.carrier.CarrierWebPage</code>.
     */
    public String getCarrierwebpage() {
        return (String) get(13);
    }

    /**
     * Setter for <code>trustgame.carrier.CarrierWebImage</code>.
     */
    public void setCarrierwebimage(byte[] value) {
        set(14, value);
    }

    /**
     * Getter for <code>trustgame.carrier.CarrierWebImage</code>.
     */
    public byte[] getCarrierwebimage() {
        return (byte[]) get(14);
    }

    /**
     * Setter for <code>trustgame.carrier.Version</code>.
     */
    public void setVersion(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>trustgame.carrier.Version</code>.
     */
    public String getVersion() {
        return (String) get(15);
    }

    /**
     * Setter for <code>trustgame.carrier.Vname</code>.
     */
    public void setVname(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>trustgame.carrier.Vname</code>.
     */
    public String getVname() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<Integer, String, String, byte[], CarrierService, CarrierSustainability, String, String, String, String, String, String, byte[], String, byte[], String, String> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<Integer, String, String, byte[], CarrierService, CarrierSustainability, String, String, String, String, String, String, byte[], String, byte[], String, String> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Carrier.CARRIER.ID;
    }

    @Override
    public Field<String> field2() {
        return Carrier.CARRIER.NAME;
    }

    @Override
    public Field<String> field3() {
        return Carrier.CARRIER.SLOGAN;
    }

    @Override
    public Field<byte[]> field4() {
        return Carrier.CARRIER.LOGO;
    }

    @Override
    public Field<CarrierService> field5() {
        return Carrier.CARRIER.SERVICE;
    }

    @Override
    public Field<CarrierSustainability> field6() {
        return Carrier.CARRIER.SUSTAINABILITY;
    }

    @Override
    public Field<String> field7() {
        return Carrier.CARRIER.COMPANYDESCRIPTION;
    }

    @Override
    public Field<String> field8() {
        return Carrier.CARRIER.WEBSITEURL;
    }

    @Override
    public Field<String> field9() {
        return Carrier.CARRIER.OFFICIALREPORTDESCRIPTION;
    }

    @Override
    public Field<String> field10() {
        return Carrier.CARRIER.OFFICIALREPORT;
    }

    @Override
    public Field<String> field11() {
        return Carrier.CARRIER.CARRIERTYPE;
    }

    @Override
    public Field<String> field12() {
        return Carrier.CARRIER.GOOGLEPAGE;
    }

    @Override
    public Field<byte[]> field13() {
        return Carrier.CARRIER.GOOGLEIMAGE;
    }

    @Override
    public Field<String> field14() {
        return Carrier.CARRIER.CARRIERWEBPAGE;
    }

    @Override
    public Field<byte[]> field15() {
        return Carrier.CARRIER.CARRIERWEBIMAGE;
    }

    @Override
    public Field<String> field16() {
        return Carrier.CARRIER.VERSION;
    }

    @Override
    public Field<String> field17() {
        return Carrier.CARRIER.VNAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getSlogan();
    }

    @Override
    public byte[] component4() {
        return getLogo();
    }

    @Override
    public CarrierService component5() {
        return getService();
    }

    @Override
    public CarrierSustainability component6() {
        return getSustainability();
    }

    @Override
    public String component7() {
        return getCompanydescription();
    }

    @Override
    public String component8() {
        return getWebsiteurl();
    }

    @Override
    public String component9() {
        return getOfficialreportdescription();
    }

    @Override
    public String component10() {
        return getOfficialreport();
    }

    @Override
    public String component11() {
        return getCarriertype();
    }

    @Override
    public String component12() {
        return getGooglepage();
    }

    @Override
    public byte[] component13() {
        return getGoogleimage();
    }

    @Override
    public String component14() {
        return getCarrierwebpage();
    }

    @Override
    public byte[] component15() {
        return getCarrierwebimage();
    }

    @Override
    public String component16() {
        return getVersion();
    }

    @Override
    public String component17() {
        return getVname();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getSlogan();
    }

    @Override
    public byte[] value4() {
        return getLogo();
    }

    @Override
    public CarrierService value5() {
        return getService();
    }

    @Override
    public CarrierSustainability value6() {
        return getSustainability();
    }

    @Override
    public String value7() {
        return getCompanydescription();
    }

    @Override
    public String value8() {
        return getWebsiteurl();
    }

    @Override
    public String value9() {
        return getOfficialreportdescription();
    }

    @Override
    public String value10() {
        return getOfficialreport();
    }

    @Override
    public String value11() {
        return getCarriertype();
    }

    @Override
    public String value12() {
        return getGooglepage();
    }

    @Override
    public byte[] value13() {
        return getGoogleimage();
    }

    @Override
    public String value14() {
        return getCarrierwebpage();
    }

    @Override
    public byte[] value15() {
        return getCarrierwebimage();
    }

    @Override
    public String value16() {
        return getVersion();
    }

    @Override
    public String value17() {
        return getVname();
    }

    @Override
    public CarrierRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CarrierRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CarrierRecord value3(String value) {
        setSlogan(value);
        return this;
    }

    @Override
    public CarrierRecord value4(byte[] value) {
        setLogo(value);
        return this;
    }

    @Override
    public CarrierRecord value5(CarrierService value) {
        setService(value);
        return this;
    }

    @Override
    public CarrierRecord value6(CarrierSustainability value) {
        setSustainability(value);
        return this;
    }

    @Override
    public CarrierRecord value7(String value) {
        setCompanydescription(value);
        return this;
    }

    @Override
    public CarrierRecord value8(String value) {
        setWebsiteurl(value);
        return this;
    }

    @Override
    public CarrierRecord value9(String value) {
        setOfficialreportdescription(value);
        return this;
    }

    @Override
    public CarrierRecord value10(String value) {
        setOfficialreport(value);
        return this;
    }

    @Override
    public CarrierRecord value11(String value) {
        setCarriertype(value);
        return this;
    }

    @Override
    public CarrierRecord value12(String value) {
        setGooglepage(value);
        return this;
    }

    @Override
    public CarrierRecord value13(byte[] value) {
        setGoogleimage(value);
        return this;
    }

    @Override
    public CarrierRecord value14(String value) {
        setCarrierwebpage(value);
        return this;
    }

    @Override
    public CarrierRecord value15(byte[] value) {
        setCarrierwebimage(value);
        return this;
    }

    @Override
    public CarrierRecord value16(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public CarrierRecord value17(String value) {
        setVname(value);
        return this;
    }

    @Override
    public CarrierRecord values(Integer value1, String value2, String value3, byte[] value4, CarrierService value5, CarrierSustainability value6, String value7, String value8, String value9, String value10, String value11, String value12, byte[] value13, String value14, byte[] value15, String value16, String value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CarrierRecord
     */
    public CarrierRecord() {
        super(Carrier.CARRIER);
    }

    /**
     * Create a detached, initialised CarrierRecord
     */
    public CarrierRecord(Integer id, String name, String slogan, byte[] logo, CarrierService service, CarrierSustainability sustainability, String companydescription, String websiteurl, String officialreportdescription, String officialreport, String carriertype, String googlepage, byte[] googleimage, String carrierwebpage, byte[] carrierwebimage, String version, String vname) {
        super(Carrier.CARRIER);

        setId(id);
        setName(name);
        setSlogan(slogan);
        setLogo(logo);
        setService(service);
        setSustainability(sustainability);
        setCompanydescription(companydescription);
        setWebsiteurl(websiteurl);
        setOfficialreportdescription(officialreportdescription);
        setOfficialreport(officialreport);
        setCarriertype(carriertype);
        setGooglepage(googlepage);
        setGoogleimage(googleimage);
        setCarrierwebpage(carrierwebpage);
        setCarrierwebimage(carrierwebimage);
        setVersion(version);
        setVname(vname);
    }
}
