/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.transsonic.trustgame.data.trustgame.tables.Client;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientRecord extends UpdatableRecordImpl<ClientRecord> implements Record6<Integer, String, byte[], String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.client.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.client.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.client.Name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.client.Name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>trustgame.client.Logo</code>.
     */
    public void setLogo(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.client.Logo</code>.
     */
    public byte[] getLogo() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>trustgame.client.Type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.client.Type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>trustgame.client.Version</code>.
     */
    public void setVersion(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustgame.client.Version</code>.
     */
    public String getVersion() {
        return (String) get(4);
    }

    /**
     * Setter for <code>trustgame.client.Vname</code>.
     */
    public void setVname(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustgame.client.Vname</code>.
     */
    public String getVname() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, byte[], String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, byte[], String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Client.CLIENT.ID;
    }

    @Override
    public Field<String> field2() {
        return Client.CLIENT.NAME;
    }

    @Override
    public Field<byte[]> field3() {
        return Client.CLIENT.LOGO;
    }

    @Override
    public Field<String> field4() {
        return Client.CLIENT.TYPE;
    }

    @Override
    public Field<String> field5() {
        return Client.CLIENT.VERSION;
    }

    @Override
    public Field<String> field6() {
        return Client.CLIENT.VNAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public byte[] component3() {
        return getLogo();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public String component5() {
        return getVersion();
    }

    @Override
    public String component6() {
        return getVname();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public byte[] value3() {
        return getLogo();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public String value5() {
        return getVersion();
    }

    @Override
    public String value6() {
        return getVname();
    }

    @Override
    public ClientRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ClientRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ClientRecord value3(byte[] value) {
        setLogo(value);
        return this;
    }

    @Override
    public ClientRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public ClientRecord value5(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public ClientRecord value6(String value) {
        setVname(value);
        return this;
    }

    @Override
    public ClientRecord values(Integer value1, String value2, byte[] value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientRecord
     */
    public ClientRecord() {
        super(Client.CLIENT);
    }

    /**
     * Create a detached, initialised ClientRecord
     */
    public ClientRecord(Integer id, String name, byte[] logo, String type, String version, String vname) {
        super(Client.CLIENT);

        setId(id);
        setName(name);
        setLogo(logo);
        setType(type);
        setVersion(version);
        setVname(vname);
    }
}
