/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.transsonic.trustgame.data.trustgame.tables.Fbreport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FbreportRecord extends UpdatableRecordImpl<FbreportRecord> implements Record14<Integer, Integer, String, String, String, UInteger, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.fbreport.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.fbreport.Carrier_ID</code>.
     */
    public void setCarrierId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.Carrier_ID</code>.
     */
    public Integer getCarrierId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>trustgame.fbreport.FBRegistration</code>.
     */
    public void setFbregistration(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.FBRegistration</code>.
     */
    public String getFbregistration() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trustgame.fbreport.CountryCode</code>.
     */
    public void setCountrycode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.CountryCode</code>.
     */
    public String getCountrycode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>trustgame.fbreport.Address</code>.
     */
    public void setAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.Address</code>.
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>trustgame.fbreport.FBMemberSince</code>.
     */
    public void setFbmembersince(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.FBMemberSince</code>.
     */
    public UInteger getFbmembersince() {
        return (UInteger) get(5);
    }

    /**
     * Setter for <code>trustgame.fbreport.BTWNr</code>.
     */
    public void setBtwnr(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.BTWNr</code>.
     */
    public String getBtwnr() {
        return (String) get(6);
    }

    /**
     * Setter for <code>trustgame.fbreport.ISO</code>.
     */
    public void setIso(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.ISO</code>.
     */
    public String getIso() {
        return (String) get(7);
    }

    /**
     * Setter for <code>trustgame.fbreport.Contact</code>.
     */
    public void setContact(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.Contact</code>.
     */
    public String getContact() {
        return (String) get(8);
    }

    /**
     * Setter for <code>trustgame.fbreport.Capacity</code>.
     */
    public void setCapacity(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.Capacity</code>.
     */
    public String getCapacity() {
        return (String) get(9);
    }

    /**
     * Setter for <code>trustgame.fbreport.Employees</code>.
     */
    public void setEmployees(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.Employees</code>.
     */
    public String getEmployees() {
        return (String) get(10);
    }

    /**
     * Setter for <code>trustgame.fbreport.Reliability</code>.
     */
    public void setReliability(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.Reliability</code>.
     */
    public String getReliability() {
        return (String) get(11);
    }

    /**
     * Setter for <code>trustgame.fbreport.FleetCharacteristics</code>.
     */
    public void setFleetcharacteristics(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.FleetCharacteristics</code>.
     */
    public String getFleetcharacteristics() {
        return (String) get(12);
    }

    /**
     * Setter for <code>trustgame.fbreport.OtherInfo</code>.
     */
    public void setOtherinfo(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.OtherInfo</code>.
     */
    public String getOtherinfo() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, Integer, String, String, String, UInteger, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Integer, Integer, String, String, String, UInteger, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Fbreport.FBREPORT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Fbreport.FBREPORT.CARRIER_ID;
    }

    @Override
    public Field<String> field3() {
        return Fbreport.FBREPORT.FBREGISTRATION;
    }

    @Override
    public Field<String> field4() {
        return Fbreport.FBREPORT.COUNTRYCODE;
    }

    @Override
    public Field<String> field5() {
        return Fbreport.FBREPORT.ADDRESS;
    }

    @Override
    public Field<UInteger> field6() {
        return Fbreport.FBREPORT.FBMEMBERSINCE;
    }

    @Override
    public Field<String> field7() {
        return Fbreport.FBREPORT.BTWNR;
    }

    @Override
    public Field<String> field8() {
        return Fbreport.FBREPORT.ISO;
    }

    @Override
    public Field<String> field9() {
        return Fbreport.FBREPORT.CONTACT;
    }

    @Override
    public Field<String> field10() {
        return Fbreport.FBREPORT.CAPACITY;
    }

    @Override
    public Field<String> field11() {
        return Fbreport.FBREPORT.EMPLOYEES;
    }

    @Override
    public Field<String> field12() {
        return Fbreport.FBREPORT.RELIABILITY;
    }

    @Override
    public Field<String> field13() {
        return Fbreport.FBREPORT.FLEETCHARACTERISTICS;
    }

    @Override
    public Field<String> field14() {
        return Fbreport.FBREPORT.OTHERINFO;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getCarrierId();
    }

    @Override
    public String component3() {
        return getFbregistration();
    }

    @Override
    public String component4() {
        return getCountrycode();
    }

    @Override
    public String component5() {
        return getAddress();
    }

    @Override
    public UInteger component6() {
        return getFbmembersince();
    }

    @Override
    public String component7() {
        return getBtwnr();
    }

    @Override
    public String component8() {
        return getIso();
    }

    @Override
    public String component9() {
        return getContact();
    }

    @Override
    public String component10() {
        return getCapacity();
    }

    @Override
    public String component11() {
        return getEmployees();
    }

    @Override
    public String component12() {
        return getReliability();
    }

    @Override
    public String component13() {
        return getFleetcharacteristics();
    }

    @Override
    public String component14() {
        return getOtherinfo();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getCarrierId();
    }

    @Override
    public String value3() {
        return getFbregistration();
    }

    @Override
    public String value4() {
        return getCountrycode();
    }

    @Override
    public String value5() {
        return getAddress();
    }

    @Override
    public UInteger value6() {
        return getFbmembersince();
    }

    @Override
    public String value7() {
        return getBtwnr();
    }

    @Override
    public String value8() {
        return getIso();
    }

    @Override
    public String value9() {
        return getContact();
    }

    @Override
    public String value10() {
        return getCapacity();
    }

    @Override
    public String value11() {
        return getEmployees();
    }

    @Override
    public String value12() {
        return getReliability();
    }

    @Override
    public String value13() {
        return getFleetcharacteristics();
    }

    @Override
    public String value14() {
        return getOtherinfo();
    }

    @Override
    public FbreportRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FbreportRecord value2(Integer value) {
        setCarrierId(value);
        return this;
    }

    @Override
    public FbreportRecord value3(String value) {
        setFbregistration(value);
        return this;
    }

    @Override
    public FbreportRecord value4(String value) {
        setCountrycode(value);
        return this;
    }

    @Override
    public FbreportRecord value5(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public FbreportRecord value6(UInteger value) {
        setFbmembersince(value);
        return this;
    }

    @Override
    public FbreportRecord value7(String value) {
        setBtwnr(value);
        return this;
    }

    @Override
    public FbreportRecord value8(String value) {
        setIso(value);
        return this;
    }

    @Override
    public FbreportRecord value9(String value) {
        setContact(value);
        return this;
    }

    @Override
    public FbreportRecord value10(String value) {
        setCapacity(value);
        return this;
    }

    @Override
    public FbreportRecord value11(String value) {
        setEmployees(value);
        return this;
    }

    @Override
    public FbreportRecord value12(String value) {
        setReliability(value);
        return this;
    }

    @Override
    public FbreportRecord value13(String value) {
        setFleetcharacteristics(value);
        return this;
    }

    @Override
    public FbreportRecord value14(String value) {
        setOtherinfo(value);
        return this;
    }

    @Override
    public FbreportRecord values(Integer value1, Integer value2, String value3, String value4, String value5, UInteger value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FbreportRecord
     */
    public FbreportRecord() {
        super(Fbreport.FBREPORT);
    }

    /**
     * Create a detached, initialised FbreportRecord
     */
    public FbreportRecord(Integer id, Integer carrierId, String fbregistration, String countrycode, String address, UInteger fbmembersince, String btwnr, String iso, String contact, String capacity, String employees, String reliability, String fleetcharacteristics, String otherinfo) {
        super(Fbreport.FBREPORT);

        setId(id);
        setCarrierId(carrierId);
        setFbregistration(fbregistration);
        setCountrycode(countrycode);
        setAddress(address);
        setFbmembersince(fbmembersince);
        setBtwnr(btwnr);
        setIso(iso);
        setContact(contact);
        setCapacity(capacity);
        setEmployees(employees);
        setReliability(reliability);
        setFleetcharacteristics(fleetcharacteristics);
        setOtherinfo(otherinfo);
    }
}
