/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.transsonic.trustgame.data.trustgame.tables.Game;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameRecord extends UpdatableRecordImpl<GameRecord> implements Record8<Integer, String, Integer, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.game.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.game.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.game.Name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.game.Name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>trustgame.game.Mission_ID</code>.
     */
    public void setMissionId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.game.Mission_ID</code>.
     */
    public Integer getMissionId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>trustgame.game.TextFinishDay</code>.
     */
    public void setTextfinishday(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.game.TextFinishDay</code>.
     */
    public String getTextfinishday() {
        return (String) get(3);
    }

    /**
     * Setter for <code>trustgame.game.TextReview</code>.
     */
    public void setTextreview(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustgame.game.TextReview</code>.
     */
    public String getTextreview() {
        return (String) get(4);
    }

    /**
     * Setter for <code>trustgame.game.TextAllReviews</code>.
     */
    public void setTextallreviews(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustgame.game.TextAllReviews</code>.
     */
    public String getTextallreviews() {
        return (String) get(5);
    }

    /**
     * Setter for <code>trustgame.game.Version</code>.
     */
    public void setVersion(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>trustgame.game.Version</code>.
     */
    public String getVersion() {
        return (String) get(6);
    }

    /**
     * Setter for <code>trustgame.game.Vname</code>.
     */
    public void setVname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>trustgame.game.Vname</code>.
     */
    public String getVname() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, Integer, String, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, Integer, String, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Game.GAME.ID;
    }

    @Override
    public Field<String> field2() {
        return Game.GAME.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Game.GAME.MISSION_ID;
    }

    @Override
    public Field<String> field4() {
        return Game.GAME.TEXTFINISHDAY;
    }

    @Override
    public Field<String> field5() {
        return Game.GAME.TEXTREVIEW;
    }

    @Override
    public Field<String> field6() {
        return Game.GAME.TEXTALLREVIEWS;
    }

    @Override
    public Field<String> field7() {
        return Game.GAME.VERSION;
    }

    @Override
    public Field<String> field8() {
        return Game.GAME.VNAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getMissionId();
    }

    @Override
    public String component4() {
        return getTextfinishday();
    }

    @Override
    public String component5() {
        return getTextreview();
    }

    @Override
    public String component6() {
        return getTextallreviews();
    }

    @Override
    public String component7() {
        return getVersion();
    }

    @Override
    public String component8() {
        return getVname();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getMissionId();
    }

    @Override
    public String value4() {
        return getTextfinishday();
    }

    @Override
    public String value5() {
        return getTextreview();
    }

    @Override
    public String value6() {
        return getTextallreviews();
    }

    @Override
    public String value7() {
        return getVersion();
    }

    @Override
    public String value8() {
        return getVname();
    }

    @Override
    public GameRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GameRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GameRecord value3(Integer value) {
        setMissionId(value);
        return this;
    }

    @Override
    public GameRecord value4(String value) {
        setTextfinishday(value);
        return this;
    }

    @Override
    public GameRecord value5(String value) {
        setTextreview(value);
        return this;
    }

    @Override
    public GameRecord value6(String value) {
        setTextallreviews(value);
        return this;
    }

    @Override
    public GameRecord value7(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public GameRecord value8(String value) {
        setVname(value);
        return this;
    }

    @Override
    public GameRecord values(Integer value1, String value2, Integer value3, String value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameRecord
     */
    public GameRecord() {
        super(Game.GAME);
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(Integer id, String name, Integer missionId, String textfinishday, String textreview, String textallreviews, String version, String vname) {
        super(Game.GAME);

        setId(id);
        setName(name);
        setMissionId(missionId);
        setTextfinishday(textfinishday);
        setTextreview(textreview);
        setTextallreviews(textallreviews);
        setVersion(version);
        setVname(vname);
    }
}
